name: Go Security Scan

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: go mod tidy

      # Step 4: Set Working Directory
      - name: Set Working Directory
        run: cd ${{ github.workspace }}

      # Step 5: Run gosec for security analysis
      - name: Run gosec
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.17.0
          ./bin/gosec ./...

      # Step 6: Run golangci-lint for linting (optional but recommended)
      - name: Run GolangCI-Lint
        run: golangci-lint run ./...
        working-directory: ./Hosting-ServerCore


      # Step 7: Run Trivy for dependency scanning
      - name: Run Trivy
        run: |
          curl -sfL https://aquasecurity.github.io/trivy/install.sh | sh
          ./trivy fs .
